function Health_Monitoring_System()
% HEALTH MONITORING SYSTEM - Main Application
% A complete patient health data management system

% Clear any existing figures
close all;
clc;

% Get screen dimensions
screenSize = get(0, 'ScreenSize');
screenWidth = screenSize(3);
screenHeight = screenSize(4);

% Create main figure
mainFig = figure('Name', 'Health Monitoring System', ...
    'NumberTitle', 'off', ...
    'Position', [screenWidth/4, screenHeight/4, 600, 450], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Color', [0.9 0.95 0.98], ...
    'Resize', 'off');

% Header panel
headerPanel = uipanel('Parent', mainFig, ...
    'Title', '', ...
    'Position', [0 0.8 1 0.2], ...
    'BackgroundColor', [0.2 0.4 0.6], ...
    'BorderType', 'none');

% Title
uicontrol('Parent', headerPanel, ...
    'Style', 'text', ...
    'String', 'HEALTH MONITORING SYSTEM', ...
    'FontSize', 24, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', 'white', ...
    'BackgroundColor', [0.2 0.4 0.6], ...
    'Position', [100, 30, 400, 40]);

% Subtitle
uicontrol('Parent', headerPanel, ...
    'Style', 'text', ...
    'String', 'Patient Management Portal', ...
    'FontSize', 14, ...
    'FontWeight', 'normal', ...
    'ForegroundColor', [0.9 0.95 1], ...
    'BackgroundColor', [0.2 0.4 0.6], ...
    'Position', [150, 5, 300, 25]);

% Main content area
contentPanel = uipanel('Parent', mainFig, ...
    'Title', '', ...
    'Position', [0 0 1 0.8], ...
    'BackgroundColor', [0.95 0.98 0.99], ...
    'BorderType', 'none');

% Welcome text
uicontrol('Parent', contentPanel, ...
    'Style', 'text', ...
    'String', 'Welcome to Health Monitoring System', ...
    'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [0.2 0.2 0.4], ...
    'BackgroundColor', [0.95 0.98 0.99], ...
    'Position', [100, 280, 400, 30]);

% Description
uicontrol('Parent', contentPanel, ...
    'Style', 'text', ...
    'String', 'Manage patient registrations and health data collection', ...
    'FontSize', 12, ...
    'ForegroundColor', [0.4 0.4 0.4], ...
    'BackgroundColor', [0.95 0.98 0.99], ...
    'Position', [100, 250, 400, 25]);

% Button panel
btnPanel = uipanel('Parent', contentPanel, ...
    'Title', 'Select Option', ...
    'Position', [0.15 0.15 0.7 0.5], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'ForegroundColor', [0.2 0.4 0.6], ...
    'FontWeight', 'bold', ...
    'BorderWidth', 1);

% Registration Button
registerBtn = uicontrol('Parent', btnPanel, ...
    'Style', 'pushbutton', ...
    'String', 'REGISTER PATIENT', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.2 0.6 0.4], ...
    'ForegroundColor', 'white', ...
    'Position', [75, 120, 250, 40], ...
    'Callback', @openRegistration);

% Login Button
loginBtn = uicontrol('Parent', btnPanel, ...
    'Style', 'pushbutton', ...
    'String', 'PATIENT LOGIN', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.2 0.5 0.8], ...
    'ForegroundColor', 'white', ...
    'Position', [75, 60, 250, 40], ...
    'Callback', @openLogin);

% Exit Button
exitBtn = uicontrol('Parent', contentPanel, ...
    'Style', 'pushbutton', ...
    'String', 'EXIT SYSTEM', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.8 0.3 0.3], ...
    'ForegroundColor', 'white', ...
    'Position', [450, 20, 120, 35], ...
    'Callback', @(src,event) close(mainFig));

% Footer
uicontrol('Parent', contentPanel, ...
    'Style', 'text', ...
    'String', '© ACTIVE GALAXY', ...
    'FontSize', 10, ...
    'ForegroundColor', [0.5 0.5 0.5], ...
    'BackgroundColor', [0.95 0.98 0.99], ...
    'Position', [200, 10, 200, 20]);

% Center the figure
movegui(mainFig, 'center');

% Callback functions for main menu
    function openRegistration(~, ~)
        createRegistrationGUI();
    end

    function openLogin(~, ~)
        createLoginGUI();
    end
end

%% -------------------- REGISTRATION GUI --------------------
function createRegistrationGUI()
% Create registration window
screenSize = get(0, 'ScreenSize');
regFig = figure('Name', 'Patient Registration', ...
    'NumberTitle', 'off', ...
    'Position', [screenSize(3)/3, screenSize(4)/4, 500, 450], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Color', [0.95 0.98 0.97], ...
    'Resize', 'off');

% Header
headerPanel = uipanel('Parent', regFig, ...
    'Title', '', ...
    'Position', [0 0.85 1 0.15], ...
    'BackgroundColor', [0.1 0.5 0.3], ...
    'BorderType', 'none');

uicontrol('Parent', headerPanel, ...
    'Style', 'text', ...
    'String', 'NEW PATIENT REGISTRATION', ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', 'white', ...
    'BackgroundColor', [0.1 0.5 0.3], ...
    'Position', [50, 15, 400, 35]);

% Main form panel
formPanel = uipanel('Parent', regFig, ...
    'Title', 'Patient Details', ...
    'Position', [0.05 0.1 0.9 0.7], ...
    'BackgroundColor', [0.98 0.995 0.99], ...
    'ForegroundColor', [0.2 0.4 0.3], ...
    'FontWeight', 'bold', ...
    'BorderWidth', 1);

% Name field
uicontrol('Parent', formPanel, ...
    'Style', 'text', ...
    'String', 'Full Name:', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.2 0.4 0.3], ...
    'BackgroundColor', [0.98 0.995 0.99], ...
    'Position', [30, 200, 100, 25]);

nameField = uicontrol('Parent', formPanel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [140, 200, 250, 30]);

% Mobile field
uicontrol('Parent', formPanel, ...
    'Style', 'text', ...
    'String', 'Mobile:', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.2 0.4 0.3], ...
    'BackgroundColor', [0.98 0.995 0.99], ...
    'Position', [30, 150, 100, 25]);

mobileField = uicontrol('Parent', formPanel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [140, 150, 250, 30]);

% Password field
uicontrol('Parent', formPanel, ...
    'Style', 'text', ...
    'String', 'Password:', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.2 0.4 0.3], ...
    'BackgroundColor', [0.98 0.995 0.99], ...
    'Position', [30, 100, 100, 25]);

passwordField = uicontrol('Parent', formPanel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [140, 100, 250, 30], ...
    'Enable', 'inactive');

% Password visibility checkbox
showPassCheck = uicontrol('Parent', formPanel, ...
    'Style', 'checkbox', ...
    'String', 'Show Password', ...
    'FontSize', 10, ...
    'ForegroundColor', [0.2 0.4 0.3], ...
    'BackgroundColor', [0.98 0.995 0.99], ...
    'Position', [140, 70, 120, 25], ...
    'Callback', @togglePasswordVisibility);

% Store password data
passwordData = '';
setappdata(regFig, 'passwordStore', passwordData);
set(passwordField, 'KeyPressFcn', @(src, evt) handlePasswordKey(src, evt, regFig));

% Button panel
buttonPanel = uipanel('Parent', regFig, ...
    'Title', '', ...
    'Position', [0.05 0.02 0.9 0.08], ...
    'BackgroundColor', [0.96 0.98 0.96], ...
    'BorderType', 'none');

% Register button
uicontrol('Parent', buttonPanel, ...
    'Style', 'pushbutton', ...
    'String', 'REGISTER', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.2 0.6 0.4], ...
    'ForegroundColor', 'white', ...
    'Position', [50, 10, 100, 35], ...
    'Callback', @registerPatient);

% Clear button
uicontrol('Parent', buttonPanel, ...
    'Style', 'pushbutton', ...
    'String', 'CLEAR', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.95 0.6 0.2], ...
    'ForegroundColor', 'white', ...
    'Position', [170, 10, 100, 35], ...
    'Callback', @clearFields);

% Back button
uicontrol('Parent', buttonPanel, ...
    'Style', 'pushbutton', ...
    'String', 'BACK', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.6 0.6 0.6], ...
    'ForegroundColor', 'white', ...
    'Position', [290, 10, 100, 35], ...
    'Callback', @(src, event) close(regFig));

% Center the figure
movegui(regFig, 'center');

% Nested callback functions
    function togglePasswordVisibility(~, ~)
        if get(showPassCheck, 'Value')
            set(passwordField, 'Enable', 'on');
        else
            set(passwordField, 'Enable', 'inactive');
        end
    end

    function handlePasswordKey(src, evt, fig)
        storedPass = getappdata(fig, 'passwordStore');
        if isempty(storedPass)
            storedPass = '';
        end
        
        switch evt.Key
            case 'backspace'
                if ~isempty(storedPass)
                    storedPass = storedPass(1:end-1);
                end
            case 'delete'
                storedPass = '';
            otherwise
                if ~isempty(evt.Character) && ~any(strcmp(evt.Key, {'backspace', 'delete', 'return', 'escape'}))
                    storedPass = [storedPass evt.Character];
                end
        end
        
        setappdata(fig, 'passwordStore', storedPass);
        set(src, 'String', repmat('*', 1, length(storedPass)));
    end

    function clearFields(~, ~)
        set(nameField, 'String', '');
        set(mobileField, 'String', '');
        set(passwordField, 'String', '');
        setappdata(regFig, 'passwordStore', '');
        set(showPassCheck, 'Value', 0);
        togglePasswordVisibility();
    end

    function registerPatient(~, ~)
        name = strtrim(get(nameField, 'String'));
        mobile = strtrim(get(mobileField, 'String'));
        password = getappdata(regFig, 'passwordStore');
        
        % Validation
        if isempty(name)
            errordlg('Please enter patient name.', 'Validation Error');
            return;
        end
        
        if isempty(mobile) || ~all(isdigit(mobile)) || length(mobile) ~= 10
            errordlg('Please enter a valid 10-digit mobile number.', 'Validation Error');
            return;
        end
        
        if isempty(password) || length(password) < 4
            errordlg('Password must be at least 4 characters long.', 'Validation Error');
            return;
        end
        
        % Load existing users
        users = loadUsers();
        
        % Check if mobile already exists
        for i = 1:length(users)
            if strcmp(users(i).Mobile, mobile)
                errordlg('This mobile number is already registered.', 'Duplicate Error');
                return;
            end
        end
        
        % Check maximum users limit
        if length(users) >= 10
            errordlg('Maximum number of patients (10) reached.', 'Limit Error');
            return;
        end
        
        % Create new user
        newUser.Name = name;
        newUser.Mobile = mobile;
        newUser.Password = password;
        
        % Add to users array
        if isempty(users)
            users = newUser;
        else
            users(end+1) = newUser;
        end
        
        % Save users
        saveUsers(users);
        
        % Show success message
        msgbox(sprintf('Patient %s registered successfully!', name), 'Success', 'modal');
        
        % Clear fields
        clearFields();
    end

    function result = isdigit(str)
        result = all(isstrprop(str, 'digit'));
    end
end

%% -------------------- LOGIN GUI --------------------
function createLoginGUI()
% Create login window
screenSize = get(0, 'ScreenSize');
loginFig = figure('Name', 'Patient Login', ...
    'NumberTitle', 'off', ...
    'Position', [screenSize(3)/3, screenSize(4)/3, 450, 350], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Color', [0.94 0.97 0.99], ...
    'Resize', 'off');

% Header
headerPanel = uipanel('Parent', loginFig, ...
    'Title', '', ...
    'Position', [0 0.85 1 0.15], ...
    'BackgroundColor', [0.2 0.4 0.7], ...
    'BorderType', 'none');

uicontrol('Parent', headerPanel, ...
    'Style', 'text', ...
    'String', 'PATIENT LOGIN', ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', 'white', ...
    'BackgroundColor', [0.2 0.4 0.7], ...
    'Position', [100, 15, 250, 35]);

% Login form panel
formPanel = uipanel('Parent', loginFig, ...
    'Title', 'Enter Credentials', ...
    'Position', [0.05 0.2 0.9 0.6], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'ForegroundColor', [0.2 0.3 0.5], ...
    'FontWeight', 'bold', ...
    'BorderWidth', 1);

% Mobile field
uicontrol('Parent', formPanel, ...
    'Style', 'text', ...
    'String', 'Mobile:', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.2 0.3 0.5], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'Position', [30, 120, 100, 25]);

mobileField = uicontrol('Parent', formPanel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [140, 120, 200, 30]);

% Password field
uicontrol('Parent', formPanel, ...
    'Style', 'text', ...
    'String', 'Password:', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.2 0.3 0.5], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'Position', [30, 70, 100, 25]);

passwordField = uicontrol('Parent', formPanel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [140, 70, 200, 30], ...
    'Enable', 'inactive');

% Password visibility checkbox
showPassCheck = uicontrol('Parent', formPanel, ...
    'Style', 'checkbox', ...
    'String', 'Show Password', ...
    'FontSize', 10, ...
    'ForegroundColor', [0.2 0.3 0.5], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'Position', [140, 40, 120, 25], ...
    'Callback', @togglePasswordVisibility);

% Store password data
passwordData = '';
setappdata(loginFig, 'passwordStore', passwordData);
set(passwordField, 'KeyPressFcn', @(src, evt) handlePasswordKey(src, evt, loginFig));

% Button panel
buttonPanel = uipanel('Parent', loginFig, ...
    'Title', '', ...
    'Position', [0.05 0.05 0.9 0.12], ...
    'BackgroundColor', [0.96 0.98 0.99], ...
    'BorderType', 'none');

% Login button
uicontrol('Parent', buttonPanel, ...
    'Style', 'pushbutton', ...
    'String', 'LOGIN', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.2 0.6 0.8], ...
    'ForegroundColor', 'white', ...
    'Position', [80, 10, 100, 35], ...
    'Callback', @loginPatient);

% Back button
uicontrol('Parent', buttonPanel, ...
    'Style', 'pushbutton', ...
    'String', 'BACK', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.6 0.6 0.6], ...
    'ForegroundColor', 'white', ...
    'Position', [200, 10, 100, 35], ...
    'Callback', @(src, event) close(loginFig));

% Center the figure
movegui(loginFig, 'center');

% Nested callback functions
    function togglePasswordVisibility(~, ~)
        if get(showPassCheck, 'Value')
            set(passwordField, 'Enable', 'on');
        else
            set(passwordField, 'Enable', 'inactive');
        end
    end

    function handlePasswordKey(src, evt, fig)
        storedPass = getappdata(fig, 'passwordStore');
        if isempty(storedPass)
            storedPass = '';
        end
        
        switch evt.Key
            case 'backspace'
                if ~isempty(storedPass)
                    storedPass = storedPass(1:end-1);
                end
            case 'delete'
                storedPass = '';
            otherwise
                if ~isempty(evt.Character) && ~any(strcmp(evt.Key, {'backspace', 'delete', 'return', 'escape'}))
                    storedPass = [storedPass evt.Character];
                end
        end
        
        setappdata(fig, 'passwordStore', storedPass);
        set(src, 'String', repmat('*', 1, length(storedPass)));
    end

    function loginPatient(~, ~)
        mobile = strtrim(get(mobileField, 'String'));
        password = getappdata(loginFig, 'passwordStore');
        
        % Validation
        if isempty(mobile)
            errordlg('Please enter mobile number.', 'Validation Error');
            return;
        end
        
        if isempty(password)
            errordlg('Please enter password.', 'Validation Error');
            return;
        end
        
        % Load users
        users = loadUsers();
        
        if isempty(users)
            errordlg('No patients registered yet.', 'Login Error');
            return;
        end
        
        % Find user with matching mobile
        userFound = false;
        userName = '';
        for i = 1:length(users)
            if strcmp(users(i).Mobile, mobile)
                userFound = true;
                userName = users(i).Name;
                % Check password
                if strcmp(users(i).Password, password)
                    % Login successful - open health data GUI
                    close(loginFig);
                    createHealthDataGUI(userName, mobile);
                    return;
                else
                    errordlg('Incorrect password.', 'Login Error');
                    return;
                end
            end
        end
        
        if ~userFound
            errordlg('Mobile number not registered.', 'Login Error');
        end
    end
end

%% -------------------- HEALTH DATA COLLECTION GUI --------------------
function createHealthDataGUI(userName, userMobile)
% Create health data collection window
screenSize = get(0, 'ScreenSize');
healthFig = figure('Name', 'Health Data Collection', ...
    'NumberTitle', 'off', ...
    'Position', [screenSize(3)/6, screenSize(4)/6, 800, 600], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Color', [0.96 0.98 0.99], ...
    'Resize', 'off');

% Header
headerPanel = uipanel('Parent', healthFig, ...
    'Title', '', ...
    'Position', [0 0.9 1 0.1], ...
    'BackgroundColor', [0.3 0.5 0.7], ...
    'BorderType', 'none');

uicontrol('Parent', headerPanel, ...
    'Style', 'text', ...
    'String', 'HEALTH DATA COLLECTION', ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', 'white', ...
    'BackgroundColor', [0.3 0.5 0.7], ...
    'Position', [200, 15, 400, 35]);

% Patient info panel
infoPanel = uipanel('Parent', healthFig, ...
    'Title', 'Patient Information', ...
    'Position', [0.05 0.75 0.9 0.14], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'ForegroundColor', [0.2 0.4 0.6], ...
    'FontWeight', 'bold', ...
    'BorderWidth', 1);

% Patient name
uicontrol('Parent', infoPanel, ...
    'Style', 'text', ...
    'String', 'Patient Name:', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.3 0.3 0.3], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'Position', [50, 30, 100, 25]);

uicontrol('Parent', infoPanel, ...
    'Style', 'text', ...
    'String', userName, ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'Position', [160, 30, 200, 25]);

% Mobile number
uicontrol('Parent', infoPanel, ...
    'Style', 'text', ...
    'String', 'Mobile:', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.3 0.3 0.3], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'Position', [300, 30, 100, 25]);

uicontrol('Parent', infoPanel, ...
    'Style', 'text', ...
    'String', userMobile, ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'Position', [410, 30, 200, 25]);

% Date
currentDate = datestr(now, 'dd-mmm-yyyy HH:MM');
uicontrol('Parent', infoPanel, ...
    'Style', 'text', ...
    'String', ['Date: ' currentDate], ...
    'FontSize', 10, ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.4 0.4 0.4], ...
    'BackgroundColor', [0.97 0.985 0.995], ...
    'Position', [500, 20, 170, 20]);

% Health data panel
dataPanel = uipanel('Parent', healthFig, ...
    'Title', 'Enter Health Parameters', ...
    'Position', [0.05 0.15 0.9 0.58], ...
    'BackgroundColor', [0.98 0.99 0.995], ...
    'ForegroundColor', [0.2 0.4 0.6], ...
    'FontWeight', 'bold', ...
    'BorderWidth', 1);

% Column 1 - Vital Signs
col1Panel = uipanel('Parent', dataPanel, ...
    'Title', 'Vital Signs', ...
    'Position', [0.05 0.05 0.45 0.9], ...
    'BackgroundColor', [0.985 0.995 0.99], ...
    'ForegroundColor', [0.3 0.5 0.3], ...
    'FontWeight', 'bold');

% Blood Pressure
uicontrol('Parent', col1Panel, ...
    'Style', 'text', ...
    'String', 'BP (mmHg):', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.2 0.4 0.4], ...
    'BackgroundColor', [0.985 0.995 0.99], ...
    'Position', [20, 200, 140, 25]);

bpField = uicontrol('Parent', col1Panel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [170, 200, 150, 30], ...
    'TooltipString', 'Format: 120/80');

% Blood Sugar
uicontrol('Parent', col1Panel, ...
    'Style', 'text', ...
    'String', 'Sugar (mg/dL):', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.2 0.4 0.4], ...
    'BackgroundColor', [0.985 0.995 0.99], ...
    'Position', [20, 150, 140, 25]);

sugarField = uicontrol('Parent', col1Panel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [170, 150, 150, 30], ...
    'TooltipString', 'Fasting level');

% Heart Rate
uicontrol('Parent', col1Panel, ...
    'Style', 'text', ...
    'String', 'Heart Rate (bpm):', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.2 0.4 0.4], ...
    'BackgroundColor', [0.985 0.995 0.99], ...
    'Position', [20, 100, 140, 25]);

hrField = uicontrol('Parent', col1Panel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [170, 100, 150, 30], ...
    'TooltipString', 'Beats per minute');

% Column 2 - Additional Parameters
col2Panel = uipanel('Parent', dataPanel, ...
    'Title', 'Additional Parameters', ...
    'Position', [0.55 0.05 0.45 0.9], ...
    'BackgroundColor', [0.985 0.99 0.995], ...
    'ForegroundColor', [0.5 0.3 0.5], ...
    'FontWeight', 'bold');

% SPO2
uicontrol('Parent', col2Panel, ...
    'Style', 'text', ...
    'String', 'SPO2 (%):', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.4 0.3 0.5], ...
    'BackgroundColor', [0.985 0.99 0.995], ...
    'Position', [20, 200, 140, 25]);

spo2Field = uicontrol('Parent', col2Panel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [170, 200, 150, 30], ...
    'TooltipString', 'Oxygen saturation');

% Cholesterol
uicontrol('Parent', col2Panel, ...
    'Style', 'text', ...
    'String', 'Cholesterol (mg/dL):', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.4 0.3 0.5], ...
    'BackgroundColor', [0.985 0.99 0.995], ...
    'Position', [20, 150, 140, 25]);

cholField = uicontrol('Parent', col2Panel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [170, 150, 150, 30], ...
    'TooltipString', 'Total cholesterol');

% Temperature
uicontrol('Parent', col2Panel, ...
    'Style', 'text', ...
    'String', 'Temperature (°C):', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'ForegroundColor', [0.4 0.3 0.5], ...
    'BackgroundColor', [0.985 0.99 0.995], ...
    'Position', [20, 100, 140, 25]);

tempField = uicontrol('Parent', col2Panel, ...
    'Style', 'edit', ...
    'String', '', ...
    'FontSize', 11, ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', [0.1 0.1 0.1], ...
    'Position', [170, 100, 150, 30], ...
    'TooltipString', 'Body temperature');

% Button panel
buttonPanel = uipanel('Parent', healthFig, ...
    'Title', '', ...
    'Position', [0.05 0.05 0.9 0.08], ...
    'BackgroundColor', [0.96 0.98 0.99], ...
    'BorderType', 'none');

% Save button
uicontrol('Parent', buttonPanel, ...
    'Style', 'pushbutton', ...
    'String', 'SAVE DATA', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.2 0.6 0.4], ...
    'ForegroundColor', 'white', ...
    'Position', [180, 10, 120, 35], ...
    'Callback', @saveHealthData);

% Clear button
uicontrol('Parent', buttonPanel, ...
    'Style', 'pushbutton', ...
    'String', 'CLEAR ALL', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.95 0.6 0.2], ...
    'ForegroundColor', 'white', ...
    'Position', [320, 10, 120, 35], ...
    'Callback', @clearFields);

% Exit button
uicontrol('Parent', buttonPanel, ...
    'Style', 'pushbutton', ...
    'String', 'EXIT', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.7 0.2 0.2], ...
    'ForegroundColor', 'white', ...
    'Position', [460, 10, 120, 35], ...
    'Callback', @(src, event) close(healthFig));

% Status bar
statusBar = uipanel('Parent', healthFig, ...
    'Title', '', ...
    'Position', [0 0 1 0.02], ...
    'BackgroundColor', [0.2 0.4 0.6], ...
    'BorderType', 'none');

uicontrol('Parent', statusBar, ...
    'Style', 'text', ...
    'String', 'Ready to enter health data', ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', 'white', ...
    'BackgroundColor', [0.2 0.4 0.6], ...
    'Position', [10, 2, 300, 15]);

% Center the figure
movegui(healthFig, 'center');

% Set focus to first field
uicontrol(bpField);

% Nested callback functions
    function clearFields(~, ~)
        set(bpField, 'String', '');
        set(sugarField, 'String', '');
        set(hrField, 'String', '');
        set(spo2Field, 'String', '');
        set(cholField, 'String', '');
        set(tempField, 'String', '');
    end

    function saveHealthData(~, ~)
        % Get values from fields
        bp = strtrim(get(bpField, 'String'));
        sugar = strtrim(get(sugarField, 'String'));
        hr = strtrim(get(hrField, 'String'));
        spo2 = strtrim(get(spo2Field, 'String'));
        chol = strtrim(get(cholField, 'String'));
        temp = strtrim(get(tempField, 'String'));
        
        % Validation
        if isempty(bp)
            errordlg('Please enter Blood Pressure.', 'Validation Error');
            uicontrol(bpField);
            return;
        end
        
        if isempty(sugar)
            errordlg('Please enter Blood Sugar level.', 'Validation Error');
            uicontrol(sugarField);
            return;
        end
        
        if isempty(hr)
            errordlg('Please enter Heart Rate.', 'Validation Error');
            uicontrol(hrField);
            return;
        end
        
        if isempty(spo2)
            errordlg('Please enter SPO2 level.', 'Validation Error');
            uicontrol(spo2Field);
            return;
        end
        
        if isempty(chol)
            errordlg('Please enter Cholesterol level.', 'Validation Error');
            uicontrol(cholField);
            return;
        end
        
        if isempty(temp)
            errordlg('Please enter Temperature.', 'Validation Error');
            uicontrol(tempField);
            return;
        end
        
        % Numeric validation
        try
            % Check BP format
            if ~contains(bp, '/')
                error('Blood Pressure must be in format: systolic/diastolic (e.g., 120/80)');
            end
            
            % Convert to numeric
            sugarNum = str2double(sugar);
            hrNum = str2double(hr);
            spo2Num = str2double(spo2);
            cholNum = str2double(chol);
            tempNum = str2double(temp);
            
            % Validate ranges
            if isnan(sugarNum) || sugarNum <= 0 || sugarNum > 500
                error('Blood Sugar must be between 1-500 mg/dL');
            end
            
            if isnan(hrNum) || hrNum <= 0 || hrNum > 250
                error('Heart Rate must be between 1-250 bpm');
            end
            
            if isnan(spo2Num) || spo2Num < 0 || spo2Num > 100
                error('SPO2 must be between 0-100%');
            end
            
            if isnan(cholNum) || cholNum <= 0 || cholNum > 500
                error('Cholesterol must be between 1-500 mg/dL');
            end
            
            if isnan(tempNum) || tempNum < 30 || tempNum > 45
                error('Temperature must be between 30-45°C');
            end
            
        catch ME
            errordlg(ME.message, 'Validation Error');
            return;
        end
        
        % Create health data structure
        healthData = struct();
        healthData.PatientName = userName;
        healthData.Mobile = userMobile;
        healthData.BloodPressure = bp;
        healthData.BloodSugar = sugarNum;
        healthData.HeartRate = hrNum;
        healthData.SPO2 = spo2Num;
        healthData.Cholesterol = cholNum;
        healthData.Temperature = tempNum;
        healthData.RecordDate = datestr(now, 'dd-mm-yyyy HH:MM:SS');
        
        % Create safe filename
        safeName = strrep(userName, ' ', '_');
        safeName = regexprep(safeName, '[^a-zA-Z0-9_]', '');
        filename = sprintf('HealthData_%s_%s.mat', safeName, userMobile);
        
        % Save individual file
        save(filename, 'healthData');
        filename = sprintf('HealthData.mat');
        save(filename, 'healthData');
        % Save to master records
        saveToMasterRecords(healthData);
        
        % Show success message
        msgbox(sprintf('Health data saved successfully!\n\nPatient: %s\nFile: %s', userName, filename), ...
            'Success', 'modal');
        run('SDD.m');
        % Clear fields
        clearFields();
    end
end

%% -------------------- HELPER FUNCTIONS --------------------
function users = loadUsers()
% Load users from file
if exist('users.mat', 'file')
    data = load('users.mat');
    if isfield(data, 'users')
        users = data.users;
    else
        users = [];
    end
else
    users = [];
end
end

function saveUsers(users)
% Save users to file
save('users.mat', 'users');
end

function saveToMasterRecords(healthData)
% Save health data to master records file
masterFile = 'master_health_records.mat';

if exist(masterFile, 'file')
    data = load(masterFile);
    if isfield(data, 'masterRecords')
        masterRecords = data.masterRecords;
        % Check if this is the first record or need to append
        if isstruct(masterRecords) && isfield(masterRecords, 'PatientName')
            % Convert to cell array if single struct
            masterRecords = {masterRecords};
        end
        masterRecords{end+1} = healthData;
    else
        masterRecords = {healthData};
    end
else
    masterRecords = {healthData};
end

save(masterFile, 'masterRecords');
end